version: '3.8'
services:
  mysql:
    image: docker.io/yuritech/mysql-database:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: client_management
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  client-management:
    image: docker.io/yuritech/client-management-backend:latest
    container_name: client_management_container
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/client_management
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123
    depends_on:
      - mysql

volumes:
  db_data:
