name: Build and Push Docker Images for Backend and Database

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  REGISTRY: docker.io
  BACKEND_IMAGE_NAME: yuritech/client-management-backend
  MYSQL_IMAGE_NAME: yuritech/mysql-database

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Start MySQL with Docker Compose
        run: docker-compose up -d mysql

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be ready..."
          until docker-compose exec mysql mysqladmin ping --silent; do
            echo "Waiting for MySQL..."
            sleep 5
          done
          echo "MySQL is ready!"

      - name: Build the backend with Maven
        run: mvn clean package

      - name: Run Tests
        run: mvn test

      - name: Build and Run with Docker Compose
        run: docker-compose up -d --build

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag and Push Backend Image
        run: |
          docker tag clientmanagement-client-management:latest ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:latest

      - name: Tag and Push MySQL Image
        run: |
          docker tag mysql:8.0 ${{ env.REGISTRY }}/${{ env.MYSQL_IMAGE_NAME }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.MYSQL_IMAGE_NAME }}:latest

      - name: Shutdown and Cleanup
        run: docker-compose down
