name: Build, Push, and Deploy Backend with Docker Compose

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  REGISTRY: docker.io
  BACKEND_IMAGE_NAME: yuritech/client-management-backend
  DB_IMAGE_NAME: yuritech/mysql-database

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # Passo 2: Configurar o Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Passo 3: Login no Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Passo 4: Configurar o JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      # Passo 5: Construir o backend usando Maven
      - name: Build the backend project using Maven
        run: mvn clean package -DskipTests

      # Passo 6: Construir e enviar a imagem do backend para o Docker Hub
      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:latest

      # Passo 7: Criar Dockerfile para o banco de dados MySQL
      - name: Create Dockerfile for MySQL
        run: |
          echo "FROM mysql:8.0" > Dockerfile-db
          echo "ENV MYSQL_ROOT_PASSWORD=123" >> Dockerfile-db
          echo "ENV MYSQL_DATABASE=client_management" >> Dockerfile-db

      # Passo 8: Construir e enviar a imagem do banco de dados para o Docker Hub
      - name: Build and push MySQL Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile-db
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.DB_IMAGE_NAME }}:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Conectar-se via SSH à instância EC2
      - name: SSH and Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.AWS_EC2_IP }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            # Clonar ou atualizar o repositório na instância EC2
            if [ ! -d "~/client-management" ]; then
              git clone https://github.com/seu-usuario/seu-repositorio.git ~/client-management
            else
              cd ~/client-management
              git pull origin master
            fi

            cd ~/client-management

            # Substituir as imagens no docker-compose.yml pelo repositório atualizado
            sed -i "s|image:.*mysql:8.0|image: ${{ env.REGISTRY }}/${{ env.DB_IMAGE_NAME }}:latest|" docker-compose.yml
            sed -i "s|build: .|image: ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:latest|" docker-compose.yml

            # Garantir que o Docker Compose está instalado
            if ! [ -x "$(command -v docker-compose)" ]; then
              sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            # Remover as imagens antigas, se existirem
            docker rmi ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:latest || true
            docker rmi ${{ env.REGISTRY }}/${{ env.DB_IMAGE_NAME }}:latest || true

            # Parar e remover contêineres existentes
            docker-compose down || true

            # Subir os serviços usando Docker Compose
            docker-compose up -d

            # Validar contêineres em execução
            docker ps
