name: Docker Image CI/CD

on:
  push:
    branches:
      - main  # Execute o workflow apenas nos pushes para a branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/client-management:latest

    - name: Verify Docker image
      run: |
        docker run --rm ${{ secrets.DOCKER_HUB_USERNAME }}/client-management:latest java -version
