name: Build, Push, and Deploy with Docker Compose

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  REGISTRY: docker.io
  BACKEND_IMAGE_NAME: yuritech/client-management-backend
  DB_IMAGE_NAME: yuritech/mysql-database

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build the backend project using Maven
        run: mvn clean package -DskipTests

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:latest

      - name: Create Dockerfile for MySQL
        run: |
          echo "FROM mysql:8.0" > Dockerfile-db
          echo "ENV MYSQL_ROOT_PASSWORD=123" >> Dockerfile-db
          echo "ENV MYSQL_DATABASE=client_management" >> Dockerfile-db

      - name: Build and push MySQL Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile-db
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.DB_IMAGE_NAME }}:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: SSH and Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.AWS_EC2_IP }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            # Criar diretório para o projeto se não existir
            mkdir -p ~/client-management

      - name: Copy docker-compose.yml to EC2
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.AWS_EC2_IP }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          source: ./docker-compose.yml
          target: ~/client-management/

      - name: Deploy with Docker Compose
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.AWS_EC2_IP }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd ~/client-management

            # Substituir as imagens no docker-compose.yml pelo repositório atualizado
            sed -i "s|image:.*mysql:8.0|image: ${{ env.REGISTRY }}/${{ env.DB_IMAGE_NAME }}:latest|" docker-compose.yml
            sed -i "s|build: .|image: ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:latest|" docker-compose.yml

            # Parar e remover todos os contêineres existentes
            docker-compose down || true

            # Iniciar os serviços usando o Docker Compose
            docker-compose up -d

            # Validar os contêineres em execução
            docker ps
